spring:
    main:
        web-application-type: none
    application:
        name: middleware
    profiles:
        active: local
bf:
    hadoop:
        default:
            url: nomean
    yarn:
        default:
            url: nomean
