spring:
    main:
        web-application-type: none
    application:
        name: middleware
    profiles:
        active: local
bf:
    hadoop:
        enabled: 'hz'
        default:
            url: nomean
    yarn:
        default:
#            url: nomean
    datasource:
        enabled: 'bf-security'
